# Generated by Django 2.2.2 on 2020-08-18 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agri_preneurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=75)),
                ('adresse_physique', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=75)),
                ('contact_phone', models.CharField(max_length=13)),
                ('date_inscr', models.DateTimeField(default=datetime.datetime(2020, 8, 18, 8, 16, 50, 971380, tzinfo=utc), verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'agri_preneurs',
                'ordering': ['date_inscr'],
            },
        ),
    ]
