# Generated by Django 2.2.2 on 2020-08-18 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agri_preneurs',
            name='date_inscr',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
    ]
