# Generated by Django 2.2.2 on 2020-08-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0002_auto_20200818_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agri_preneurs',
            old_name='designation',
            new_name='denomination',
        ),
    ]
