# Generated by Django 2.2.2 on 2020-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0003_auto_20200825_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=75)),
                ('prix_unit', models.FloatField(verbose_name='Prix Unitaire')),
                ('devise_vente', models.CharField(max_length=10)),
                ('qty_stock', models.IntegerField()),
                ('description', models.TextField(null='True')),
                ('image_produit', models.CharField(max_length=255, null='true')),
                ('categorie', models.CharField(max_length=75)),
                ('denomination', models.CharField(max_length=75, verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'produits',
                'ordering': ['designation'],
            },
        ),
    ]
