# Generated by Django 2.2.2 on 2020-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0004_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='agri_preneurs',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
