# Generated by Django 2.2.2 on 2020-08-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0005_agri_preneurs_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agri_preneurs',
            new_name='Agri_preneur',
        ),
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
    ]
