# Generated by Django 2.2.2 on 2020-08-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0006_auto_20200830_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agri_preneur',
            options={'ordering': ['date_inscr'], 'verbose_name': 'agri_preneur'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['designation'], 'verbose_name': 'produit'},
        ),
    ]
