# Generated by Django 2.2.2 on 2020-09-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0007_auto_20200830_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='agri_preneur',
            name='img_profils',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
