# Generated by Django 2.2.2 on 2020-09-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0008_agri_preneur_img_profils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agri_preneur',
            old_name='img_profils',
            new_name='img_profil',
        ),
    ]
