# Generated by Django 2.2.2 on 2020-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0009_auto_20200903_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agri_preneur',
            name='img_profil',
            field=models.ImageField(null=True, upload_to='static/img/', verbose_name='Image de profil'),
        ),
    ]
