# Generated by Django 2.2.2 on 2020-09-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0010_auto_20200903_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agri_preneur',
            name='img_profil',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Image de profil'),
        ),
    ]
