# Generated by Django 2.2.2 on 2020-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0011_auto_20200907_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agri_preneur',
            name='img_profil',
            field=models.ImageField(null=True, upload_to='renommage', verbose_name='Image de profil'),
        ),
    ]
